# Generated by Django 4.1 on 2024-01-07 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_api_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api_key',
            old_name='id',
            new_name='key',
        ),
    ]
